mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/polls/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),


]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length = 100)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    choice_text = models.CharField(max_length= 200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
        return render(request, 'polls/detail.html', {'question': question, 'error_message': 'Please select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args={question_id},))

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Simple Polls App</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'polls/bootstrap-4.4.1-dist/css/bootstrap.min.css' %}" />
    </head>
<body>
<hr>
<p> header</p>
<hr>
{% include "polls/header.html" %}
<div class="jumbotron">
    <div class="container">

        {% block main_content %}
        {% endblock %}
        {% include 'polls/footer.html' %}
    </div>
</div>

</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1 id="question_text">{{question.question_text}}</h1>

{% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}
<form action = "{% url 'polls:vote' question.id%}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input id="vote_button" type="submit" class="btn btn-success" value="Vote"/>
</form>
<a href="{% url 'polls:index' %}">Back to Question List</a>
{% endblock %}

mysite/polls/templates/polls/footer.html
<footer class="container">
  <p>&copy; Company 2017-2019</p>
</footer>

mysite/polls/templates/polls/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Polls</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}
<h1 class="display-3" id="polls_heading">Choose a Question</h1>
<ul>
 {% if latest_questions %}
    {% for question in latest_questions %}
    <li name="question_text">  <a name="question_link" href = "{% url 'polls:detail' question.id %}"> <b>{{question.question_text}}</b></a>  </li>
    {% endfor %}
</ul>

{% else %}
<p id="polls_empty">No Polls are available</p>
{% endif %}

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1 id="question_text">{{question.question_text}}</h1>
<ul>

    {% for choice in question.choice_set.all %}
        <li name="choice"> {{choice.choice_text}} == {{choice.votes}} vote{{choice.votes|pluralize}} </li>
    {% endfor %}
</ul>
<a href="{%url 'polls:detail' question.id %}">Vote Again?</a>
{% endblock %}